name: NekoLobby
version: '1.0-SNAPSHOT'
main: neko.nekoLobby.NekoLobby
api-version: '1.21'
authors: [ 不穿胖次の小奶猫 ]
website: https://cnmsb.xin/
commands:
  spawn:
    description: 设置或传送至出生点
    usage: /spawn set
